### ISSUE TITLE
Identical Avro elements from HadoopFileSource

### ISSUE THREAD

**Issue by nevillelyh** [GoogleCloudPlatform/DataflowJavaSDK#102]
RecordReader in AvroKeyInputFormat reuses records and result in identical elements in the output `PCollection`.

We might have to deep copy `AvroKey#datum` deep inside `HadoopFileSource` to avoid such duplicates.

**Comment by nevillelyh** [comment]
The following hack fixes the problem but that assumes `K === AvroKey[GenericRecord]`. With a `SpecificRecord` type `T` we'll have to pass the `Class<T>` in there for the copying.

```
@@ -374,6 +380,12 @@ public class HadoopFileSource<K, V> extends BoundedSource<KV<K, V>> {
       if (key instanceof Writable) {
         key = (K) WritableUtils.clone((Writable) key, conf);
       }
+      if (key instanceof AvroKey) {
+        GenericRecord r = (GenericRecord) ((AvroKey) key).datum();
+        Coder<GenericRecord> c = AvroCoder.of(Vector.getClassSchema());
+        byte[] bytes = CoderUtils.encodeToByteArray(c, r);
+        key = (K) new AvroKey(CoderUtils.decodeFromByteArray(c, bytes));
+      }
       if (value instanceof Writable) {
         value = (V) WritableUtils.clone((Writable) value, conf);
       }
```

**Comment by nevillelyh** [comment]
So basically for `SpecificRecord` I'll have to either modify `HadoopFileSource` to allow a custom copy `DoFn` or extend the class with such logic in its `BoundedReader`. What do you think?

**Comment by dhalperi** [comment]
Hi Neville,

Can you please say more about the problem with reusing the same object instance in an output collection? Elements in PCollections should never be modified, so I don't see how this will cause a problem.

**Comment by nevillelyh** [comment]
When using AvroKeyInputFormat, `K` is actually `AvroKey<T>` where `T` (`.datum()`) is the actual data record one wants, either a `GenericRecord` or subtype of `SpecificRecord`. However `RecordReader` in `Avro*InputFormat` reuses the `AvroKey` and record instance by resetting the fields every time `nextKeyValue()` is called. So by the time they make it to a bundle (or whatever in memory collection) in a `PCollection`, all of them will point to the same underlying record.

It can be reproduced by reading an Avro file with `HadoopFileSource` and printing every element in a `DoFn` right after.

**Comment by dhalperi** [comment]
Thanks for the clarification! We'll look into it.

**Comment by dhalperi** [comment]
I'm not a Hadoop export, but it looks like this is simply a bug in either Hadoop or Avro -- clone() doesn't really clone. I also found this [4-year-old, unresolved bug](https://issues.apache.org/jira/browse/AVRO-964) filed against Avro.

It looks like [`WritableUtils.cloneInto()`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/WritableUtils.java#L233) would do the trick, because it actually serializes the records. To call it, you need a new instance.. and you get can get a new instance from [`ReflectionUtils.newInstance`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/ReflectionUtils.java#L123), which is what `WritableUtils.clone` uses before it uses `copy` rather than actual cloning.

Would you be willing to give that a try?

**Comment by nevillelyh** [comment]
None of `AvroKey`, `GenericRecord`, or `SpecificRecord` is sub-type of `Writable`, so `cloneInto` will throw a `ClassCastException`.

**Comment by nevillelyh** [comment]
Pushed a PR https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/103 to demonstrate a working Avro Source.
There's also a working sink in that branch.

**Comment by davorbonaci** [comment]
Great, thanks @nevillelyh for many improvements here! We are following up in pull request #103.

**Comment by dhalperi** [comment]
Resolved, I think both here and in Apache Beam.
