### ISSUE TITLE
DoFn.apply doesn't support generic parameter DoFn implementation

### ISSUE THREAD

**Issue by rantibi** [GoogleCloudPlatform/DataflowJavaSDK#298]
I have try to create the following class:

```
@AllArgsConstructor
public class JsonToObject<T extends Serializable> extends DoFn<String, T> {

    private Class clazz;


    @Override
    public void processElement(DoFn<String, T>.ProcessContext processContext) throws Exception {
        String json = processContext.element();
        ObjectMapper mapper = new ObjectMapper();
        mapper.setAnnotationIntrospector(new JacksonLombokAnnotationIntrospector());
        T cdr = (T) mapper.readValue(json, clazz);
        processContext.output(cdr);
    }
}
```

Then try the following action:

```
PCollection<String> lines = ...
...
lines.apply("JsonToObject", ParDo.of(new JsonToObject<SomeObject>(SomeObject.class)))
```

And I got the following exception:

> java.lang.IllegalStateException: Unable to return a default Coder for JsonToCdr.out [PCollection]. Correct one of the following root causes:
>   No Coder has been manually specified;  you may do so using .setCoder().
>   Inferring a Coder from the CoderRegistry failed: Cannot provide a coder for type variable T (declared by class com.juno.bi.dataflow.core.transforms.JsonToObject) because the actual type is unknown due to erasure.
>   Using the default output Coder from the producing PTransform failed: Cannot provide a coder for type variable T (declared by class com.juno.bi.dataflow.core.transforms.JsonToObject) because the actual type is unknown due to erasure.

**Since `T extends Serializable` I found no reason that `SerializableCoder` isn't choosen in this case.**
For this reason, if I want to use my code I have to set the coder by my self.

The reason for this bug is that n the following [code line](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderRegistry.java#L696), it use only `typeDescriptor.getType()` but not searching for the super classes like it handle with concrete classes using [`FallbackCoderProvider`](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderRegistry.java#L333)

**Comment by kennknowles** [comment]
Thanks for the report! I agree that this could be made to work. There are two parts to my reply:

1. In general, it is not safe to traverse supertypes looking for coders, since coders are used for both encoding and decoding.
2. But `Serializable` is not a real supertype, so it actually is safe and I think your example is a good one and it should work.

#### 1. Not safe to search supertypes

The shortest answer is that `Coder<T>` is [invariant](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Formal_definition) in `T`.

Here is a more detailed explanation in the context of Dataflow/Beam. Suppose you have these two classes and a registered coder:

```java
class Parent { ... }
class Child extends Parent { ... }

Coder<Parent> parentCoder = ...;
pipeline.getCoderRegistry().registerDefaultCoder(Parent.class, parentCoder);
```

This ASCII art is my quickest explanation of why this `Coder<Parent>` is not a `Coder<Child>`.

```
                               -----------------
Child is a Parent --(encode)---| Coder<Parent> |--(decode)---> Parent is NOT a Child
                               -----------------
```

In code, elsewhere in your pipeline you have

```java
PCollection<Child> childCollection = ...
```

If we were to search parent classes, then to find a coder for `childCollection`, we would look for a coder for `Child.class` and search its parent class `Parent.class`, coming up with `parentCoder`.

This will encode without crashing - every element is a `Child` so it is also an instance of `Parent` - but it may drop fields that `Child` added. For decoding, it will generally fail - the `parentCoder` will decode the bytes and return a `Parent` object, which is not an instance of `Child`, so we have broken type safety.

#### 2. `T extends Serializable` can work

Since `Serializable` is not a real supertype but just a marker interface, it is safe to use, and we do so [in SerializableCoder.PROVIDER](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/SerializableCoder.java#L91). I think that with slight modification, this coder provider will return a coder when you have `T extends Serializable`.

I believe the place to address the problem is [this line]( https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderRegistry.java#L715) that only calls [`getDefaultCoder(Class)`](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderRegistry.java#L310) if the type is actually a `Class` object, when it could also work for a `TypeVariable`.

**Comment by kennknowles** [comment]
This is filed as [BEAM-328](https://issues.apache.org/jira/browse/BEAM-328).
