### ISSUE TITLE
access pubsub message attributes

### ISSUE THREAD

**Issue by mammothbane** [GoogleCloudPlatform/DataflowJavaSDK#321]
As far as I know, there's currently no way to get to the `attributes` field on a pubsub message, but I need it for some custom signing metadata on both the `Read` and `Write` ends of the pipeline. Is there a supported way to do this, or should I just write my own `PTransform`s?

**Comment by dhalperi** [comment]
Hey Nathan,

Thanks. This is an important feature request but unfortunately it is not currently supported by `PubSubIO`. You can work around this at the producer side by including the metadata in your message payload itself.

Alternately, you may fork PubSubIO and modify PubsubUnboundedSource or PubsubUnboundedSink to support this new feature.

Since Dataflow has been moving to Beam, this is tracked as part of This is being tracked as part of [BEAM-404](https://issues.apache.org/jira/browse/BEAM-404)

**Comment by dhalperi** [comment]
This has been added in the latest release (2.0.0-beta3) of [Dataflow SDK for Java 2.x](https://cloud.google.com/dataflow/release-notes/release-notes-java-2) based on [Apache Beam](https://beam.apache.org).
