### ISSUE TITLE
Write compressed files

### ISSUE THREAD

**Issue by ElPicador** [GoogleCloudPlatform/DataflowJavaSDK#404]
It's possible to read from compressed files, it would be useful to be able to write compressed files as well.

**Comment by aseure** [comment]
+1

**Comment by nevillelyh** [comment]
Also +1, especially for AvroIO

**Comment by jeffkpayne** [comment]
Not sure why this isn't getting more traction.  I just implemented a solution that should be general enough to easily allow for multiple compression schemes, in addition to file level encryption, or anything that needs to decorate/transform the raw output that's usually just written to `Channels.newOutputStream(channel)`, eg, in the TextIO classes.

Waiting to hear from work on whether I can open a PR with this code (shouldn't be an issue).  Will do so ASAP once I get permission.

**Comment by dhalperi** [comment]
Until SDK 1.7.0, Dataflow actually only supported writing certain files through special support in the Cloud Dataflow service, and so we could not add new functionality. Now, however, we do have that ability.

Note that there is a good reason this was not originally supported: Compressing output files is generally terrible for downstream processing. Most consumers of files perform very poorly when reading from them (Examples: Dataflow and Google BigQuery are both unable to parallelize reads from compressed files).

At Google, we highly discourage compressed data but prefer, e.g., block-compressed formats like Avro that combine compression and the ability to seek/split/parallelize reading. AvroIO DOES support compression.

That said, a PR would be a welcome improvement. However, new features are not being accepted to Dataflow before they go into Apache Beam, so that we do not have regressions when we migrate to Beam in Dataflow 2.0.

Here is the [JIRA issue: BEAM-55](https://issues.apache.org/jira/browse/BEAM-55) that tracks this feature request for Beam. Suggest further discussion and work happen there.

**Comment by nevillelyh** [comment]
@dhalperi we looked at [AvroIO.java](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroIO.java) before and didn't see any reference of compression. And Avro files written with AvroIO are uncompressed. How do you enable it actually?

We actually patched AvroIO a bit to support compression codec [here](https://github.com/spotify/scio/blob/master/scio-core/src/main/java/com/google/cloud/dataflow/sdk/io/PatchedAvroIO.java#L960).

**Comment by dhalperi** [comment]
@nevillelyh Yikes -- if that's not supported, it's just an omission. Want to send a PR to Beam?

**Comment by nevillelyh** [comment]
Yes will do

**Comment by nevillelyh** [comment]
PR: https://github.com/apache/incubator-beam/pull/1038

**Comment by dhalperi** [comment]
This is supported in [Dataflow SDK for Java 2.x](https://cloud.google.com/dataflow/release-notes/release-notes-java-2) based on [Apache Beam](https://beam.apache.org).
