### ISSUE TITLE
Upgrade bigtable-client-core to 0.9

### ISSUE THREAD

**Issue by vinaykolasc** [GoogleCloudPlatform/DataflowJavaSDK#449]
The current version of `bigtable-client-core` is 0.3.0
https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/64dffc366a8ca0a33d5d717c7e52a5bbf2e30085/sdk/pom.xml#L534

0.9.0 was released in Jun 2016. Is there an upgrade plan?

In my case, this is causing issues because one of my other dependencies transitively depends on `bigtable-client-core` 0.9.1, and so consuming `google-cloud-dataflow-java-sdk-all` causes class conflicts.

I would also be interested if you have solutions for my current issue (repackaging?).

**Comment by lukecwik** [comment]
Since there is a shared gRPC dependency between bigtable and other GCP client libs, we are blocked on a GCP team to give us an updated client library (so we don't break backwards compatibility) with the newer gRPC version. In Apache Beam, we broke backwards compatibility and were already able to provide the update.

We have had some partial success in shading the gRPC artifacts and their dependencies but it depends on what your transitive dependency uses them for.

Have you tried overriding the versions in Dataflow?
bigtable-client-core 0.9.1
netty 4.1.3.Final
gRPC 1.0.1
protobuf 3.0.0

**Comment by dhalperi** [comment]
Dataflow 2.0.0-beta1 is released, which uses a newer version of the Cloud Bigtable core library.
