### ISSUE TITLE
Error "Could not obtain credential using gcloud: Cannot run program "gcloud": error=2, No such file or directory" running WordCount with DirectPipelineRunner

### ISSUE THREAD

**Issue by mindcrime** [GoogleCloudPlatform/DataflowJavaSDK#6]
I've built DataflowJavaSDK successfully, but attempting to run the WordCount example using the syntax listed in the README:

mvn exec:java -pl examples -Dexec.mainClass=com.google.cloud.dataflow.examples.WordCount -Dexec.args="--runner=DirectPipelineRunner --output=foo"

Yields this error:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:java (default-cli) on project google-cloud-dataflow-java-examples-all: An exception occured while executing the Java class. null: InvocationTargetException: Could not obtain credential using gcloud: Cannot run program "gcloud": error=2, No such file or directory -> [Help 1]

**Comment by ericandrewschmidt** [comment]
This is an issue related to whitelisting for existing Google Cloud service implementation.  Worked directly with developer to resolve.

**Comment by mindcrime** [comment]
Looks like this is mainly a documentation issue.  The instructions for local mode don't mention the need to specify a --input param with a path to a local file, so it seems to default to trying to load the cloud resource.  If README showed using a local file for running the examples locally, everything should just work.

**Comment by davorbonaci** [comment]
Hi Phillip,
Indeed, this is a doc issue. We'll fix it shortly. This is not related to whitelisting in any way.

Our WordCount example has the default input, which tries to grab Shakespeare's King Lear from a Google Cloud Storage (GCS) location. The location is a world-readable GCS bucket, so anybody can access it, but it still requires some 'gcloud' mangling.

The instructions for local execution should recommend setting '--input' as a parameter. Cloud executions using DataflowPipelineRunner should still skip this setting, because 'gcloud' auth is anyways required in that case.

Thanks for reporting this!

**Comment by davorbonaci** [comment]
I wanted to follow up that we have addressed several issues in our README.md file, including the addition of the '--input' parameter.

We'd appreciate reports of any additional issues that may come up. Thanks!
