### ISSUE TITLE
Document valid options for setWorkerDiskType

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/DataflowJavaSDK#68]
Seems like the possible options are
```
"compute.googleapis.com/projects//zones//diskTypes/pd-ssd"
"compute.googleapis.com/projects//zones//diskTypes/pd-standard"
```
(and not just "pd-ssd" or "pd-standard"). Perhaps better to make those an enum instead of magic strings?

**Comment by dhalperi** [comment]
Thanks for this report. The possible options are set by [Google Compute Engine](https://cloud.google.com/compute/docs/reference/latest/diskTypes#resource).

Using an enum sounds nice, but it would prevent users of Dataflow from using new types introduced by GCE without upgrading the SDK. Additionally, though this may be unlikely in practice, disk type availability could vary based on the zones and projects in question.

I will update the Java and help documentation for the `setWorkerDiskType(String)` function in order to provide better information for developers and users.
