### ISSUE TITLE
Geo-point property support on DatastoreIO

### ISSUE THREAD

**Issue by caioiglesias** [GoogleCloudPlatform/DataflowJavaSDK#94]
By looking at the variables on the Value type of a Map from an entity I see Geo-point is an Embedded Entity. Should a helper be implemented for it or just handle it as an embedded entity and move along?

```
 entity_value {
  property {
    name: "x"
    value {
      double_value: -23.9461
      indexed: false
    }
  }
  property {
    name: "y"
    value {
      double_value: -46.3355
      indexed: false
    }
  }
}
meaning: 9
indexed: false
```

**Comment by dhalperi** [comment]
Olá Caio,

DatastoreIO uses the Cloud Datastore APIs directly, and it returns the entities that are produced. If the Geo-point is stored in the Datastore as an entity itself, rather than as an instance of a GeoPoint class for example, all we can do is return the entity as is.

For now, after reading your entities as a `PCollection<Entity>` from `DatastoreIO.Read`, you can apply a `ParDo` transform that uses a `DoFn<Entity, YourJavaType>` converting from the entities in the raw API form into POJOs. Maybe this is what you meant by a "helper"?

We will update DatastoreIO to take advantage of any new improvements in the Cloud Datastore APIs. If, in the future, Cloud Datastore APIs change to become better unified with AppEngine APIs, we may be able to directly use AppEngine libraries that expose GeoPoint objects or Java ORM frameworks like Objectify.

Thanks!

**Comment by caioiglesias** [comment]
Sorry, I wasn't clear about the helper.

I meant helper from com.google.api.services.datastore.client.DatastoreHelper by using something similar to the available:
- DatastoreHelper.getDouble(Value v)
- DatastoreHelper.getString(Value v)
- DatastoreHelper.getLong(Value v)

and maybe: DatastoreHelper.getGeoPoint(Value v)

**Comment by caioiglesias** [comment]
Now that I'm reading the package name...

**Comment by dhalperi** [comment]
I spoke to the Cloud Datastore team. In the current (v1beta2) API of Datastore, GeoPoint is not a supported data type -- see [this list](https://cloud.google.com/datastore/docs/concepts/entities#Datastore_Properties_and_value_types).

There will likely be a GeoPoint in a future version of the API, and when there is that helper will be added.

**Comment by caioiglesias** [comment]
I appreciated the attention! Thank you!
