### ISSUE TITLE
Contrib modules to maven central

### ISSUE THREAD

**Issue by mrunesson** [GoogleCloudPlatform/DataflowJavaSDK#97]
I notice that the contrib modules are not pushed to Maven central. It would make them easier to use if they could be pushed to maven central together with each release. Preferable as one artifact per contrib module.

**Comment by davorbonaci** [comment]
True -- this would make the community-contributed modules easier to use. That said, we don't appropriately test the modules with all versions of the SDK, which makes it hard for us to provide proper guarantees.

For the time being, we'd generally prefer the individual authors to push them to Maven Central under a non-Google group, instead of us doing that.
